name: Backend CD
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: repository Checkout
        uses: actions/checkout@v3

      - name: docker image build
        run: docker build -t rlafosem/xsearch_backend ./backend

      - name: docker hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub pubilsh
        run: docker push rlafosem/xsearch_backend

      
      - name: Docker stop backend container
        run: docker stop backend

      - name: Docker remove backend image
        run: docker rmi -f rlafosem/xsearch_backend

      - name: Docker restart backend
        run: docker run -d -p 3000:3000 --name backend rlafosem/xsearch_backend
